module.exports = {
  plugins: [
    {
      name: "preset-default",
      params: {
        overrides: {
          // or disable plugins
          removeMetadata: false,
          removeTitle: false,
          removeDesc: false,
          removeHiddenElems: false,
          removeEmptyText: false,
          removeEmptyContainers: false,
          removeViewBox: false,
          cleanupEnableBackground: false,
          convertStyleToAttrs: false,
          convertColors: false,
          convertPathData: false,
          removeUnknownsAndDefaults: false,
          removeNonInheritableGroupAttrs: false,
          removeUnusedNS: false,
          cleanupNumericValues: false,
          cleanupListOfValues: false,
          moveElemsAttrsToGroup: false,
          removeRasterImages: false,
          mergePaths: false,
          sortAttrs: false,
          removeDimensions: false,
          removeAttrs: false,
          removeElementsByAttr: false,
          addClassesToSVGElement: false,
          removeStyleElement: false,
          removeScriptElement: false,
          removeHiddenElems: false,
        },
      },
    },
    // enable builtin plugin not included in default preset
    "prefixIds",
    "convertTransform",
    "convertShapeToPath",
    "moveGroupAttrsToElems",
    "collapseGroups",
  ],
};
