export const accessories: Accessory[] = [
  // Accessory that fill the 'Body' slot ->  Layer selected as 95
  {
    name: "Assassin-cap",
    slot: "Body",
    recipe: ["Cloth", "Cloth", "Cloth", "Glass", "Glass", "Metal"],
    description: "A black suit.",
    components: [{ name: "Assassin-cap", layer: 95 }],
  },
  {
    name: "Astro-suit",
    slot: "Body",
    recipe: ["Cloth", "Metal", "Circuit", "Circuit", "Circuit", "Dfinity-stone"],
    description: "A suit of spacey technology.",
    components: [{ name: "Astro-body", layer: 95 }],
  },
  {
    name: "Cronic-tshirt",
    slot: "Body",
    recipe: ["Cloth", "Cloth", "Wood", "Wood", "Dfinity-stone", "Cronic-essence"],
    description: "This tshirt reminds me of something...",
    components: [{ name: "Cronic-tshirt", layer: 95 }],
  },
  {
    name: "Devil-jacket",
    slot: "Body",
    recipe: ["Cloth", "Wood", "Wood", "Glass", "Metal", "Metal"],
    description: "A suit that scares the devil.",
    components: [{ name: "Devil-jacket", layer: 95 }],
  },
  {
    name: "Helicap-tshirt",
    slot: "Body",
    recipe: ["Cloth", "Cloth", "Cloth", "Wood", "Wood", "Metal"],
    description: "A simple helicap t-shirt.",
    components: [{ name: "Helicap-tshirt", layer: 95 }],
  },
  {
    name: "Lab-coat",
    slot: "Body",
    recipe: ["Wood", "Glass", "Glass", "Metal", "Circuit", "Circuit"],
    description: "A lab coat used to test new technologies.",
    components: [{ name: "Lab-coat", layer: 95 }],
  },
  {
    name: "Magic-cap",
    slot: "Body",
    recipe: ["Cloth", "Wood", "Wood", "Metal", "Metal", "Dfinity-stone"],
    description: "A suit of dark magic.",
    components: [{ name: "Magic-cap", layer: 95 }],
  },
  {
    name: "Shinobi-suit",
    slot: "Body",
    recipe: ["Cloth", "Wood", "Wood", "Wood", "Metal", "Metal"],
    description: "A shinobi jacket.",
    components: [{ name: "Shinobi-jacket", layer: 95 }],
  },
  // {
  //   name: "Squid-suit",
  //   slot: "Body",
  //   recipe: ["Cloth", "Cloth", "Wood", "Wood", "Glass", "Glass"],
  //   description: "todo",
  //   components: [{ name: "Squid-suit", layer: 95 }],
  // },
  {
    name: "Street-jacket",
    slot: "Body",
    recipe: ["Cloth", "Wood", "Glass", "Metal", "Circuit", "Dfinity-stone"],
    description: "A simple suit for a dystopian world.",
    components: [{ name: "Street-jacket", layer: 95 }],
  },
  {
    name: "Super-suit",
    slot: "Body",
    recipe: ["Cloth", "Wood", "Glass", "Metal", "Circuit", "Dfinity-stone"],
    description: "A suit of superpowers.",
    components: [{ name: "Super-suit", layer: 95 }],
  },
  {
    name: "Yakuza-suit",
    slot: "Body",
    recipe: ["Wood", "Wood", "Wood", "Metal", "Metal", "Metal"],
    description: "Used by the yakuza oni group to show their power.",
    components: [{ name: "Yakuza-suit", layer: 95 }],
  },

  // Accessory that fill the 'Hat' slot ->  Layer selected as 85 (so hair-top can go on top of it but not hair-middle)
  {
    name: "Assassin-hat",
    slot: "Hat",
    recipe: ["Cloth", "Wood", "Wood", "Metal"],
    description: "A hat used to hide the identity of the assassin.",
    components: [{ name: "Assassin-hat", layer: 85 }],
  },
  {
    name: "Astro-helmet",
    slot: "Hat",
    recipe: ["Metal", "Circuit", "Circuit", "Dfinity-stone"],
    description: "A helmet used to protect against radiation.",
    components: [{ name: "Astro-helmet", layer: 85 }],
  },
  {
    name: "Dark-magic-hood",
    slot: "Hat",
    recipe: ["Wood", "Wood", "Glass", "Dfinity-stone"],
    description: "A hood used to practice dark magic.",
    components: [{ name: "Dark-magic-hood", layer: 85 }],
  },
  {
    name: "Helicap",
    slot: "Hat",
    recipe: ["Cloth", "Cloth", "Wood", "Glass"],
    description: "Look mom, I can fly!",
    components: [{ name: "Helicap", layer: 85 }],
  },
  {
    name: "Marshall-hat",
    slot: "Hat",
    recipe: ["Metal", "Metal", "Metal"],
    description: "This hat gives you authority over this district. 👮",
    components: [{ name: "Marshall-hat", layer: 85 }],
  },
  {
    name: "Ninja-headband",
    slot: "Hat",
    recipe: ["Metal", "Metal", "Metal"],
    description: "I don't quit, I don't run, I never go back on my word. 🦊",
    components: [{ name: "Ninja-headband", layer: 85 }],
  },
  {
    name: "Santa-hat",
    slot: "Hat",
    recipe: ["Cloth", "Wood", "Cloth"],
    description: "Merry christmas! 🎅",
    components: [{ name: "Santa-hat", layer: 85 }],
  },
  {
    name: "Shinobi-strawhat",
    slot: "Hat",
    recipe: ["Cloth", "Wood", "Wood", "Wood"],
    description: "A straw hat used by the shinobi.",
    components: [{ name: "Shinobi-strawhat", layer: 85 }],
  },
  // Accessory that fill the 'Eyes' slot ->  Layer selected as 80
  {
    name: "Dfinity-eyemask",
    slot: "Eyes",
    recipe: ["Dfinity-stone", "Glass", "Glass"],
    description: "You can litterally see infinity... ∞",
    components: [{ name: "Dfinity-eyemask", layer: 80 }],
  },
  {
    name: "Lab-glasses",
    slot: "Eyes",
    recipe: ["Glass", "Glass", "Glass", "Circuit"],
    description: "A perfect pair of glasses for entering the lab.",
    components: [{ name: "Lab-glasses", layer: 80 }],
  },
  {
    name: "Matrix-glasses",
    slot: "Eyes",
    recipe: ["Metal", "Metal", "Metal"],
    description: "You can finally see through bullshit.",
    components: [{ name: "Matrix-glasses", layer: 80 }],
  },
  {
    name: "Monocle",
    slot: "Eyes",
    recipe: ["Metal", "Metal", "Metal"],
    description: "I'm wearing a monocle so I must be rich and famous.",
    components: [{ name: "Monocle", layer: 80 }],
  },
  // {
  //   name: "Punk-glasses",
  //   slot: "Eyes",
  //  recipe: ["Glass", "Glass", "Metal", "Punk-essence"],
  //   description: "A pair of glasses that gives you a punk look.",
  //   components: [{ name: "Punk-glasses", layer: 80 }],
  // },
  // Accessory that fill the 'Face' slot ->  Layer selected as 80
  {
    name: "Dfinity-face-mask",
    slot: "Face",
    recipe: ["Dfinity-stone", "Cloth", "Cloth"],
    description: "Facemask protecting you from any virus of the cyberspace... or maybe not.",
    components: [{ name: "Dfinity-face-mask", layer: 80 }],
  },
  {
    name: "Oni-half-mask",
    slot: "Face",
    recipe: ["Metal", "Metal", "Metal"],
    description: "A terrifying aura emanates from this mask.",
    components: [{ name: "Oni-half-mask", layer: 80 }],
  },
  // {
  //   name: "Punk-face-mask",
  //   slot: "Face",
  //  recipe: ["Cloth", "Cloth", "Punk-essence"],
  //   description: "A mask that gives you a punk look.",
  //   components: [{ name: "Punk-face-mask", layer: 80 }],
  // },
];
