import type { Inventory, ItemInventory } from "@canisters/accessories/accessories.did.d";
import type { Recipe } from "@canisters/accessories/accessories.did.d";
const recipes = {
  "shinobi-hat": ["cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood"],
  "assassin-hood": ["cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "wood", "wood", "wood", "glass", "metal", "metal", "metal"],
  "astro-helmet": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
  ],
  helicap: ["cloth", "cloth", "cloth", "cloth", "wood", "wood", "wood", "wood", "circuit", "metal"],
  "magic-hood": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "dfinity-stone",
  ],
  "marshall-hat": ["cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood", "glass", "glass", "glass", "metal", "metal", "metal", "circuit"],
  "mortaboard-hat": [],
  "ninja-headband": ["cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood", "metal", "circuit", "circuit"],
  "boring-mask": ["cloth", "cloth", "cloth", "cloth", "metal", "metal", "metal", "metal"],
  "juggalo-facemask": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "circuit",
  ],
  "oni-face-mask": ["wood", "wood", "wood", "wood", "wood", "wood", "wood", "wood", "glass", "glass", "glass", "glass", "glass", "glass", "metal", "metal", "circuit"],
  facemask: ["cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood", "wood", "wood", "wood", "metal", "metal", "metal", "metal", "metal", "metal", "metal", "circuit"],
  "gas-mask": ["cloth", "cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood", "glass", "glass", "glass", "glass", "glass", "glass", "metal", "metal", "circuit", "circuit", "circuit"],
  "kitsune-mask": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
  ],
  "evil-mask": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
  ],
  "punk-mask": ["cloth", "cloth", "cloth", "cloth", "metal", "metal", "metal", "metal", "punk-essence", "punk-essence", "punk-essence"],
  "cronic-eyepatch": ["glass", "metal", "metal", "metal", "cronic-essence", "cronic-essence"],
  "dfinity-eyemask": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "dfinity-stone",
  ],
  "lab-glasses": ["cloth", "cloth", "cloth", "cloth", "glass", "glass", "glass"],
  monocle: ["glass", "glass", "glass", "metal"],
  "punk-glasses": ["cloth", "cloth", "cloth", "cloth", "glass", "glass", "glass", "metal", "circuit", "punk-essence", "punk-essence", "punk-essence"],
  sunglasses: ["cloth", "cloth", "cloth", "cloth", "glass", "metal", "metal", "metal", "circuit"],
  "assassin-cape": ["cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood", "glass", "metal", "metal", "metal", "metal", "metal", "metal"],
  "astro-suit": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
  ],
  "bootcamp-soldier": [],
  "cronic-tshirt": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "cronic-essence",
    "cronic-essence",
  ],
  "devil-jacket": [
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
  ],
  "helicap-tshirt": ["cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "wood", "wood"],
  "lab-coat": ["cloth", "cloth", "cloth", "cloth", "wood", "wood", "wood", "wood", "wood", "wood", "wood", "wood", "glass", "glass", "metal", "circuit", "circuit"],
  "magic-cape": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
  ],
  "shinobi-suit": ["cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "cloth", "wood", "glass", "glass", "glass", "metal", "metal", "metal", "circuit", "circuit"],
  "street-jacket": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
  ],
  "yakuza-suit": ["cloth", "cloth", "cloth", "cloth", "wood", "wood", "wood", "wood", "glass", "glass", "metal", "metal", "metal", "circuit", "circuit"],
  "cronic-hypnose": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
    "dfinity-stone",
    "cronic-essence",
    "cronic-essence",
    "cronic-essence",
  ],
  "cronic-wallpaper": [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
    "dfinity-stone",
    "cronic-essence",
    "cronic-essence",
    "cronic-essence",
  ],
  snowfall: [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
    "dfinity-stone",
  ],
  sunrise: [
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "cloth",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "wood",
    "glass",
    "glass",
    "glass",
    "glass",
    "glass",
    "metal",
    "metal",
    "metal",
    "metal",
    "circuit",
    "circuit",
    "circuit",
    "dfinity-stone",
    "dfinity-stone",
  ],
};

const description = {
  "shinobi-hat": "A hat made of cloth and wood. It is worn by the squad ninja.",
  helicap: "A simple cap, not too expensive and perfect to attract attention.",
  "assassin-hood": "The perfect hood to hide your identity. KYC not required.",
  "marshall-hat": "A hat usually worn by moderators. Protect againt scammers.",
  "ninja-headband": "This headband is offered to all ninja after they've been trough their neuron locking ceremony.",
  "magic-hood": "This hood is used by the magicians of modern times.",
  "kitsune-mask": `This mask is proudly worn by the warriors of the famous 8Years-gang.\n\nDoesn't protect against liquidation.`,
  "astro-helmet": `The helmet for astronaut. Made of expensive and solid materials.\n\nCan bring you to the moon and beyond.`,
  "mortaboard-hat": `Airdropped to all students who graduated from the 1st edition of the Motoko Bootcamp.\n\nCannot be minted again.`,
  "boring-mask": "A mask made of cloth. It's not very protective but at least you can use it to hide your face whenever you want.",
  "juggalo-facemask": "The facial paint you need to join the juggalos. Not the ICP you think.",
  "oni-face-mask": "Confers protection and benediction from the spirits.",
  facemask: "Not very protective but at least this one has nice color.",
  "gas-mask": "This mask is the most protective you can find. Protect against chemicals, virus and dirty odors.",
  "evil-mask": "Only for the most evil of the squad.",
  "lab-glasses": "The pair of glasses you need when testing new recipes.",
  "punk-mask": "A scary mask to make you look like a dangerous clown. Requires 2 ICPunk essences.",
  monocle: "You can use this accessory to look rich even though you lost everything in the latest bear market.",
  sunglasses: "Any similarity with a famous movie is fortuitous.",
  "dfinity-eyemask": "Who said you can't see the future?",
  "punk-glasses": "A joyful pair of glasses, you can use it to look like a nice clown. Requires 3 ICPunk essence.",
  "cronic-eyepatch": "Available soon. Requires 2 Cronic essences.",
  "helicap-tshirt": "The most basic T-shirt you can find. It's not very stylish but you can combine it with the matching cap.",
  "assassin-cape": "The perfect cap to complete your assassin outfit.",
  "lab-coat": "This coat increases your Motoko coding abilities.",
  "shinobi-suit": "An impressive suit to hide your face. Perfect to complete your ninja outfit.",
  "yakuza-suit": "This heavy suit is a symbol of power and authority. Careful it's hot to wear.",
  "devil-jacket": "An impressive jacket made of cloth and metals. ",
  "street-jacket": "The perfect jacket to roam the streets.",
  "magic-cape": "A cap made of a multitude of high quality materials. Perfect to complete your magic outfit.",
  "astro-suit": "A must have to enter the ICP-rocket. Doesn't protect against crash landing.",
  "cronic-tshirt": "The legend says that this Tshirt was knit by Bob Bodilly himself. Requires 3 Cronic essences to be minted.",
  "bootcamp-soldier": `Airdropped to all students who graduated from the 1st edition of the Motoko Bootcamp.\n\nCannot be minted again.`,
  snowfall: "Put your jacket on. It's cold.",
  sunrise: "After the darkness, the sun always rises.",
  "cronic-hypnose": "A session of cronic hypnose can reduce your stress and increase your odds of stopping cigarettes. Requires 3 Cronic essences.",
  "cronic-wallpaper": "The perfect wallpaper for the room of your kids. Requires 3 Cronic essence.",
};

export function nameToRecipe(name: string): string[] {
  return recipes[name] ? recipes[name] : [""];
}

export function nameToDescription(name: string): string {
  return description[name] ? description[name] : "";
}

export type RecipeAnswer = { ok: string[] } | { err: string[] };

/* Before minting an accessory we need to verify that the user own the required materials, and if so keep track of the list of token identifier for those materials.
   'ok' : Returns a list of token identifier that correspond to the materials required to mint the accessory.
   'err' : Returns a list of missing materials to complete the recipe.  
 */
export function createMintTokensFromInventoryAndRecipe(recipe: Recipe, inventory: Inventory): RecipeAnswer {
  let tmp_copy_inventory = { ...inventory };
  let missing_materials: string[] = [];
  let mint_tokens: string[] = [];
  for (let material of recipe) {
    let material_token_id = nameToTokenIdentifier(material, tmp_copy_inventory);
    if (!material_token_id) {
      missing_materials.push(material);
    } else {
      mint_tokens.push(material_token_id);
      filterInventory(material_token_id, tmp_copy_inventory);
    }
  }
  if (missing_materials.length > 0) {
    return { err: missing_materials };
  } else {
    return { ok: mint_tokens };
  }
}

/* Returns the optional first TokenIdentifier that corresponds to the name of the item */
function nameToTokenIdentifier(name: string, inventory: Inventory): string | null {
  let keys = Object.keys(inventory);
  keys.forEach((key) => {
    if (itemToName(inventory[key]) === name) {
      return itemToTokenIdentifier(inventory[key]);
    }
  });
  return null;
}

function itemToName(item: ItemInventory): string {
  //@ts-ignore
  if (item.Material) {
    //@ts-ignore
    return item.Material.name.toLowerCase();
  }
  //@ts-ignore
  if (item.Accessory) {
    //@ts-ignore
    return item.Accessory.name.toLowerCase();
  }
  throw new Error("itemToName: item is not an accessory nor a material");
}

function itemToTokenIdentifier(item: ItemInventory): string {
  //@ts-ignore
  if (item.Material) {
    //@ts-ignore
    return item.Material.tokenIdentifier;
  }
  //@ts-ignore
  if (item.Accessory) {
    //@ts-ignore
    return item.Accessory.tokenIdentifier;
  }
  throw new Error("itemToTokenIdentifier: item is not an accessory or material");
}

function filterInventory(token_identifier: string, inventory: Inventory): Inventory {
  return inventory.filter((item) => itemToTokenIdentifier(item) !== token_identifier);
}
